@startuml

actor Medewerker
participant ":Systeem" as Systeem

loop voor elk ingredient in levering
    Medewerker -> Systeem:voegIngredientToeAanVoorraad((restaurantId, ingredientId, aantal)
end

Medewerker -> Systeem:getVoorraad((restaurantId)
Medewerker <-- Systeem: voorraad

@enduml