### Voeg product 2 (stoel) toe aan bestelling 2

POST http://localhost:8080/bestellingen/2/producten
Content-Type: application/json

{
  "productId": 2,
  "aantal": 2
}

### Voeg product 2 (stoel) voor de tweede keer toe aan bestelling 1 (verwacht internal server error)

POST http://localhost:8080/bestellingen/1/producten
Content-Type: application/json

{
  "productId": 2,
  "aantal": 1
}

### Plaatst bestelling 1

PATCH http://localhost:8080/bestellingen/1/plaats
Content-Type: application/json

