@startuml
hide circle



'skinparam linetype ortho

rectangle "\tAggregate Bibliotheek\t" {

    class Bibliotheek <<AR>> {
        naam
        leenUit(boek, lid)
        brengTerug(uitlening)
    }

    class Uitlening <<value object>> {
        startdatum
        einddatum
    }
}

class Lid <<Entity>> {
    naam
}

class Boek <<Entity>> {
        titel
}
Bibliotheek "1" -- "uitleningen *" Uitlening
Uitlening "1" -> "boek 1" Boek
Uitlening "1" -l-> "lid 1" Lid


@enduml